[package]
name = "ocr_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
imageproc = "0.23.0"
ndarray = "0.15.6"
ort = { version = "2.0.0-alpha.4" }
thiserror = "1.0.56"
